### ISSUE TITLE
Verify Staff Office Hours

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#13]
Hooray, office hours are reserved and on the course calendar!

https://courses.cs.washington.edu/courses/cse440/17au/calendar.html

Verify they're on your personal calendars:

- [x] Dhruv
- [x] Kailey
- [x] Nigini

Note I moved Nigini to CSE 021 for most days, but not 11/27.  It's a nicer room than CSE 007.

**Comment by higherdefender** [comment]
On my Calendar!

**Comment by nigini** [comment]
On my Calendar!

**Comment by KaileyXQChan** [comment]
Works! I'll put it in my calendar

**Comment by jayfo** [comment]
Yay!
