### ISSUE TITLE
Post Staff Images

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#15]
We need pictures!

https://courses.cs.washington.edu/courses/cse440/17au/index.html

They are displayed at a width of 150px.

**Comment by jayfo** [comment]
Started in #17.

Still need @KaileyXQChan and @jihoonsuh.

**Comment by KaileyXQChan** [comment]
Hi James,

let me know if this works!

**Comment by jayfo** [comment]
I didn't get an image, neither here nor in the email version of this?

**Comment by jihoonsuh** [comment]
![ji](https://user-images.githubusercontent.com/13344945/30893665-54d41a78-a2f4-11e7-9189-6f760e443170.jpg)
Here's my photo. Sorry for the delay

**Comment by jayfo** [comment]
Yay, done!
