### ISSUE TITLE
Create Staff Slack Channel

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#16]
I found and invited existing DUB slack accounts for Kailey, Nigini, and Jihoon.

@higherdefender and @cseeds can make accounts here, I can invite them to the channel:

https://uwdub.slack.com/

**Comment by jayfo** [comment]
I found and invited existing DUB slack accounts for Kailey, Nigini, and Jihoon.

@higherdefender and @cseeds can make accounts here, I can invite them to the channel:

https://uwdub.slack.com/

**Comment by higherdefender** [comment]
Done. I'm on uwdub slack. Please invite me to the channel.

**Comment by jayfo** [comment]
Did we ever get @cseeds, or are you a Slack holdout?
