### ISSUE TITLE
Get Staff Added to Organization

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#4]
I need a GitHub ID for each person, and need them to join the organization:

https://github.com/orgs/uwcse440/people

- [x] Christopher
- [x] Dhruv
- [X] James
- [x] Jihoon
- [x] Nigini
- [x] Kailey

**Comment by higherdefender** [comment]
Dhruv Jain's id: higherdefender

**Comment by nigini** [comment]
My id is "nigini"

**Comment by cseeds** [comment]
Chris here: cseeds

**Comment by KaileyXQChan** [comment]
Kailey here, my id is : KaileyXQChan
