### ISSUE TITLE
Get Confirmation on Staff Meeting Time

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#5]
I'd like to do these Tuesdays 2:00 to 3:30.

That's every Tuesday, from 10/3 up to and including 12/5.  

Generally in CSE 624, but on 11/28 in CSE 128.

Please confirm.  Let me know if you want an invite to my calendar item for this.

- [x] Christopher
- [x] Dhruv
- [X] James
- [x] Jihoon
- [x] Nigini
- [x] Kailey

**Comment by nigini** [comment]
I'm in.

**Comment by cseeds** [comment]
I'm good with that time. I'll take a cal invite too. Thanks!

**Comment by jayfo** [comment]
Yay confirmed!
