### ISSUE TITLE
Rename Teams in Canvas

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au17#59]
Now that they've picked project names, we need to rename their teams in Canvas.  

Please include the time as a prefix, as that makes everything easier when coordinating presentations.

9:30 - BackTrack
9:30 - SALT
9:30 - StressEraser
10:30 - SimPark
10:30 - Speech Bubble
10:30 - StudyBuddy
12:30 - amisu
12:30 - Check Yourself
12:30 - GroundMemo
12:30 - interview.io
1:30 - Cease
1:30 - Hermes
1:30 - MetaGrocer
1:30 - MOLO

**Comment by nigini** [comment]
DONE!
